apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-demo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-demo-app
  template:
    metadata:
      labels:
        app: express-demo-app
    spec:
      containers:
      - name: express-demo-app
        image: elyesbelgouthi/express-demo-app
        ports:
        - containerPort: 80