apiVersion: v1
kind: Service
metadata:
  name: express-demo-app-service
spec:
  selector:
    app: express-demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer